
-include Config.make

include ../Rule.begin

#
# tss_linux_reliability_usb
#

PROJECT = tss_linux_reliability_usb

OBJ_DIR = $(OBJS_USB)

CFLAGS += \
		-I$(RI_INC_COMMON_DIR)/ \
		-I$(RI_INC_COMMON_STUB_DIR)/ \
		-I$(RI_INC_ARCH_LINUX_DIR)/

CFLAGS += -DDRV_USB
CFLAGS += -DARCH_LINUX

TE_SRCS = $(TE_MAIN_SRCS)

TE_OBJS = $(TE_SRCS:.c=.o)

RI_LIB =$(RI_LIB_LINUX_DIR)/*.a

$(PROJECT) :: \
		$(TE_OBJS) \
		$(RI_LIB)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ \
		$(TE_OBJS) \
		$(RI_LIB) -lpthread

include ../Rule.end
